name: Fetch and Notify Workflow

on:
  schedule:
    - cron: '0 19 15,30 * *'  # Ejecuta el workflow todos los días a las 7:00 UTC
  workflow_dispatch:  # Permite ejecutar el workflow manualmente

jobs:
  fetch-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Ajusta según la versión que necesites

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install asyncpg

      - name: Run script
        env:
          DB_DSN: ${{ secrets.DB_DSN }}  # Variable de entorno para la base de datos
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: |
          python notifier.py
